### ISSUE TITLE
vally fails to read charmap on Windows, fails to parse anything with emotes in it

### ISSUE THREAD

**Issue by w3bb** [w3bb/vally#31]

**Comment by Misanu** [comment]
Note that it could be specifically my PC being dumb and may still work on my dads pc

**Comment by w3bb** [comment]
@Misanu Can you post the errors that come up? Make sure to wrap it in a codebox with three backticks like you would on Discord.

**Comment by Misanu** [comment]
```UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 239: character maps to <undefined>```
