### ISSUE TITLE
ssd!help

### ISSUE THREAD

**Issue by Misanu** [w3bb/vally#34]
A command that sends a DM outlining every command the bot will take, for users new to the bot.

**Comment by Misanu** [comment]
Also adding a ssd!instagram and ssd!youtube to this which both bring up the links would be useful

**Comment by w3bb** [comment]
@Misanu I think a better (and more concise option) would be ssd!social, which would show all the social media SSD has. I think it makes more sense to put them together than to separate arbitrarily. 

Also this is worthy of its own issue, so make another one for this.

ssd!h hypothetical would be an alias for "ssd!m help", almost makes me wonder if it might be worth it to make alias-able macro commands.
