### ISSUE TITLE
SSD Premium Counter

### ISSUE THREAD

**Issue by Misanu** [w3bb/vally#35]
(Im unsure of what supporter role will be renamed to but lets call it premium for now)

Once i make premium temporary (monthly donos) i will need an efficient way of keeping track. A command such a ssd!premium [user] [time] will notifiy me when i need to remove the role. Note that im pretty sure one of the bots removes it automatically.

**Comment by w3bb** [comment]
This will not be implemented as:

A. This is something that can already be done with core bots in the server
B. The donation bot already automatically removes roles

I'll leave this issue open for a bit to allow conversation to continue.
